name: Container Build [Staging]

on:
  push:
    branches: [ develop ]

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true


jobs:
  Build:
    runs-on: ubuntu-latest
    environment: staging
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to SCW Registry
        uses: docker/login-action@v2
        with:
          registry: rg.fr-par.scw.cloud/${{ vars.CONTAINER_ENVIRONMENT }}
          username: ${{ secrets.SCW_ACCESS_KEY_ID }}
          password: ${{ secrets.SCW_SECRET_ACCESS_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          push: true
          tags: rg.fr-par.scw.cloud/${{ vars.CONTAINER_ENVIRONMENT }}/diga_api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max


  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Dispatch for Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN_FOR_TRIGGER }}
          repository: vantis-health/therapy-infrastructure
          event-type: staging
          client-payload: '{"service": "diga-api"}'
